### ISSUE TITLE
Question:  Multiple REST endpoints in suite

### ISSUE THREAD

**Issue by mrcasablr** [kiranz/just-api#12]
Hello!

I have a few use cases where I have to test 2 different rest endpoints for a test case. For example,

When a user creates an account via POST on http://user-service I have to test if http://notify-service sent a welcome email via a GET request using the user id.

How do I test this scenario using just-api with multiple REST services?

**Comment by kiranz** [comment]
Take a look at https://kiranz.github.io/just-api/features/#intersuite-spec-dependencies

You can run dependency specs defined in another suite.

**Comment by kiranz** [comment]
I'm closing this issue.
