### ISSUE TITLE
Can't call async functions in end event for custom reports 

### ISSUE THREAD

**Issue by biasmey** [kiranz/just-api#13]
I am trying to call an async function for the `end` event for a  custom report and the app does not wait for pending callback. I think the problem is because you kill the process here 
https://github.com/kiranz/just-api/blob/e6706fdfc41deea02da9ede67c2ed30bc0c8284e/lib/launcher.js#L121

**Comment by kiranz** [comment]
@biasmey Good one. 
Can you post a reproducible scenario and steps so that I can test and fix it?

**Comment by kiranz** [comment]
Thanks @biasmey 
I'll see to a fix.

**Comment by kiranz** [comment]
A fix for this issue has been published in v1.2.1
