### ISSUE TITLE
Use return value of one request for next one

### ISSUE THREAD

**Issue by skizzo** [kiranz/just-api#20]
Hi y'all,
(how) is it possible to use one return value of a call as a parameter for the next one? This would be reeeeeally handy. 
Many thanks!

**Comment by kiranz** [comment]
You can run the previous spec as a dependency and pass it to the current test as shown here https://github.com/kiranz/just-api/blob/8ee4e7350ed86007834c0f792f1789eb778d709f/test/cli/src/suites/suitedependencies/intradependencies.suite.yml#L19

if you want to use the same data in other tests within a suite, store it in suite context and reuse 
More details can be found here https://kiranz.github.io/just-api/features/#storing-suite-test-data-in-context-for-reuse
